apiVersion: v1
kind: Service
metadata:
  name: mappers
  labels:
    app: mappers
spec:
  selector:
    app: mappers
  ports:
  - port: 8080
    name: mapper
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapper
spec:
  serviceName: "mappers"
  replicas: 3
  selector:
    matchlabels:
      app: mappers
  template:
    metadata:
      labels:
        app: mappers
    spec:
      containers:
      - name: mapreduce
        image: mapreduce:latest
        ports:
        - containerPort: 8080
          name: mapper
        env:
        - name: TYPE
          value: "MAP"
